create TABLE JOUEUR (
    Pseudo varchar(20),
    Mdp varchar(20),
    age integer,
    sexe char,
    ville varchar(20),
    CONSTRAINT pk_JOUEUR primary KEY (Pseudo)
);

CREATE TABLE PARTIE(
    CODE_PARTIE INTEGER,
    DATE_DEB DATE,
    DATE_FIN DATE,
    CONSTRAINT pk_partie PRIMARY KEY (CODE_PARTIE)
);

CREATE TABLE VAL_DE (
    CODE_DE CHAR(3),
    VAL1 INTEGER,
    VAL2 INTEGER,
    VAL3 INTEGER,
    CONSTRAINT pk_val_de PRIMARY KEY (CODE_DE)
);

CREATE TABLE RESULTAT (
    CODE_PARTIE INTEGER,
    PSEUDO VARCHAR(20),
    NB_JETON_CHARGE INTEGER,
    NB_JETON_DECHARGE INTEGER,
    CONSTRAINT pk_resultat PRIMARY KEY (CODE_PARTIE, PSEUDO),
    CONSTRAINT fk_resultat_joueur FOREIGN KEY (PSEUDO) REFERENCES JOUEUR,
    CONSTRAINT fk_resultat_partie FOREIGN KEY (CODE_PARTIE) REFERENCES PARTIE 
);


CREATE TABLE LANCER_CHARGE (
    CODE_PARTIE INTEGER,
    PSEUDO VARCHAR(20),
    NUM_LANCE INTEGER,
    CODE_DE CHAR(3),
    CONSTRAINT pk_lance_charge PRIMARY KEY (CODE_PARTIE, PSEUDO, NUM_LANCE),
    CONSTRAINT fk_lance_charge_joueur FOREIGN KEY (PSEUDO) REFERENCES JOUEUR,
    CONSTRAINT fk_lance_charge_val_de FOREIGN KEY (CODE_DE) REFERENCES VAL_DE,
    CONSTRAINT fk_lance_charge_partie FOREIGN KEY (CODE_PARTIE) REFERENCES PARTIE
);

CREATE TABLE LANCER_DECHARGE (
    CODE_PARTIE INTEGER,
    PSEUDO VARCHAR(20),
    NUM_LANCE INTEGER,
    NUM_ROUND INTEGER,
    CODE_DE CHAR(3),
    CONSTRAINT pk_lance_decharge PRIMARY KEY (CODE_PARTIE, PSEUDO, NUM_LANCE, NUM_ROUND),
    CONSTRAINT fk_lance_decharge_joueur FOREIGN KEY (PSEUDO) REFERENCES JOUEUR,
    CONSTRAINT fk_lance_decharge_de FOREIGN KEY (CODE_DE) REFERENCES VAL_DE,
    CONSTRAINT fk_lance_decharge_partie FOREIGN KEY (CODE_PARTIE) REFERENCES PARTIE
    
);

CREATE TABLE LANCE_ORDRE (
    PSEUDO VARCHAR(20),
    CODE_PARTIE INTEGER,
    CODE_DE CHAR(3),
    CONSTRAINT pk_lance_ordre PRIMARY KEY (CODE_PARTIE, PSEUDO),
    CONSTRAINT fk_lance_ordre_de FOREIGN KEY (CODE_DE) REFERENCES VAL_DE,
    CONSTRAINT fk_lance_ordre_partie FOREIGN KEY (CODE_PARTIE) REFERENCES PARTIE
);

